{% set name = "grape" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grape-{{ version }}.tar.gz
  sha256: cb594741fd0393d9e5a8861592019cba931513cd87ac408e660a4053cbccd010

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - downloaders
    - bioregistry
    - py-cpuinfo
    - ensmallen_graph >=0.8.88
    - embiggen >=0.11.85

test:
  imports:
    - grape
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AnacletoLAB/grape
  summary: GRAPE is a Rust/Python Graph Representation Learning library for Predictions and Evaluations.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dillonroach
    - isuruf
